# Generated by Django 4.1.6 on 2023-02-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='default/myproduct.jpg', null=True, upload_to='media'),
        ),
    ]
