# Generated by Django 4.1.6 on 2023-02-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
